### PR TITLE
Check idf version and update

### PR DESCRIPTION
**Pull request by JasonGlazer**

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Looks like the last one worked, but there is a flake8 formatting problem.

For reference, the Python interpreter is run from the root of the repository.  So you can either use a full file path, like you just did, or you can use a path relative to the root of the repo.  Either should work.  Looks like it's all good now though, looks nice!

**Comment by Myoldmopar** [comment]
And almost doubling the test coverage, great!

**Comment by JasonGlazer** [comment]
@Myoldmopar do you have any suggestions on how to add a unit test for locateworkflows.py since it is looking at absolute directories, I'm not sure how to add a unit test.

**Comment by JasonGlazer** [comment]
@Myoldmopar as you probably noticed, I've been struggling to put a unit test together for locateworkspace that works on Travis. I ended up giving up and made a unit test that was only run on Windows. This seems to be a permission issue so I'm not sure what else to do. If you have any suggestions, please let me know.

**Comment by Myoldmopar** [comment]
@JasonGlazer I'm back online after my time off.  Do you want me to look at this first or is there anything else more pressing at the moment?

**Comment by JasonGlazer** [comment]
This would be good. 

I spent way to much time trying to get a unit test to work. Probably would have been better for me to code something else.

**Comment by Myoldmopar** [comment]
@JasonGlazer OK, that should do it.  I re-enabled it on Linux so Travis will at least give it a try.  The root of the problem is really just that /usr/loca/bin/ and /Applications/ are not accessible to regular users.  You mentioned this in your comment above, it is indeed a permissions issue.  To workaround this easily, I just added /tmp as a search folder for finding E+.  For regular use, this will never have an E+ install in it, so it won't affect users.  And for testing, a regular user has write access, so the Travis tests will just drop the E+ install in there.  Should be good to go.

**Comment by JasonGlazer** [comment]
@Myoldmopar thanks!

**Comment by Myoldmopar** [comment]
I think we should rename that unit test.  Care if I push another commit real quick?

**Comment by JasonGlazer** [comment]
Go for it.

**Comment by JasonGlazer** [comment]
I did not end up finishing up all the work intended for this pull request but want to merge it in.

**Pull request merged**
