### PR TITLE
Output viewer buttons

### PR DESCRIPTION
**Pull request by JasonGlazer**

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@Myoldmopar could help me with the error message from Travis? It it saying the it can't find wx when I import it in a file called externalprograms.py. Any ideas?

**Comment by Myoldmopar** [comment]
Sure.  I'm trying to run it locally, but it's failing to startup because of an index error in the find program by extension function.  Here's an image showing what my `cmd` variable contains.  You are trying to split the contents of cmd by a double quote, which may be valid on Windows, but not on Linux.

image

**Comment by Myoldmopar** [comment]
Oh, yeah, we don't install wx on Travis due to so many difficulties with getting it running.  So we aren't unit testing any of the GUI related stuff.  Anything that requires wx should probably go into the `eplaunch.interface` folder and don't worry about writing unit tests, at least not ones that Travis will run.  We _could_ consider adding unit tests that we only run locally where we _do_ have wx installed...

**Comment by JasonGlazer** [comment]
Ok, I will make the code sensitive to the platform when using the GetOpenCommand.

Thanks for the reminder about wx and Travis.

**Comment by Myoldmopar** [comment]
Sure, and don't just throw away the failing wx-dependent tests.  We can keep unit tests to cover wx-dependent parts, and we can run them locally, we'll just tell Travis not to run them.

**Comment by JasonGlazer** [comment]
@Myoldmopar can you trying pulling this down and see if my fix for the cmd issue that you identified on Linux is fixed?

**Comment by Myoldmopar** [comment]
That does help, but it's crashing due to the ft variable being "None".  Presumably we are trying a file extension for which my computer doesn't have a default program.  If you can handle the ft being None case then it should be good to go.  (Maybe just: `if not ft: return not_found_application_path`)

**Comment by JasonGlazer** [comment]
I added that and did some other fixes. Can you try it again? If it works, I will merge this.

**Comment by Myoldmopar** [comment]
Yeah, looks like that last one took care of it.  App starts and I can run an E+ workflow on a file.

**Pull request merged**
