### PR TITLE
Cache file support

### PR DESCRIPTION
**Pull request by Myoldmopar**
This branch will start building out support for the per-folder cache files that will persist workflow state during navigation. This branch is built on top of the workflow branch, so it looks like a lot of diffs, but it's not so far.  Just one new class file and an exceptions file.

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@Myoldmopar either let me know when you are finished with each of these pull requests and I will merge them or you could merge them also.

**Comment by Myoldmopar** [comment]
Soooo, workflows and cache files just bonded.  This one is going to be building on both of them simultaneously.  You can feel free to merge in the workflows branch, it did include some valuable work for sure.

Here's what this one does now today:
 - Reads a JSON cache file, for now a fake one, but ultimately it will become the file that is dropped onto each user's directory where they run workflows
 - Gets UI column names from the workflow scripts themselves, so that as you change workflows, the columns change - it then gets the data for each column from the cached workflow file!

Try running it and changing the workflow to EnergyPlus SI and see both the columns and the values get updated!

**Comment by Myoldmopar** [comment]
@JasonGlazer ( @mjwitte ) could we have a web meeting tomorrow to look over this stuff?  It's getting fleshed out nicely but I don't want to get too far ahead of myself.

**Comment by JasonGlazer** [comment]
@Myoldmopar a call sounds good. Sometime Wednesday morning would be better for me.

**Comment by Myoldmopar** [comment]
I'm good tomorrow morning, before 10 CDT would be best.

**Comment by JasonGlazer** [comment]
Just sent out Gotomeeting invite for 9am

**Comment by Myoldmopar** [comment]
This is now "functional", as in the file lists look at the actual folder for files, and it reads/writes cache files to the actual folder.  I encourage you to drop an IDF in a test folder, browse to that folder with ep-launch-3, select the EnergyPlus SI workflow, and run it.  Wait 5 seconds, and the workflow should complete successfully, and the file list will be updated with made up results.  There will also be a hidden `.eplaunch3` file in that folder.  If you browse around to other folders and come back, it should pick up that file.  Next step is really to update all the other workflows to match the base class changes, and then modify the script to actually run E+.

**Comment by Myoldmopar** [comment]
This is starting to get a bit ridiculous.  Adding CalcSoilSurfTemp was dead simple.  We'll need to figure out a way to abstract the hard coded path to the binaries, but for now this is great.

**Comment by JasonGlazer** [comment]
This is looking good. It is great that the pieces are working well. Are you done with this phase of the cache work? If so I will merge this pull request.

**Comment by Myoldmopar** [comment]
You are welcome to merge anytime, I'm not going to be able to touch it
anymore until after merit and peer reviews are done.  We should pow-wow a
bit about the development process though.  Right now the workflow scripts
are pointing at hardcoded paths to executables.  Eventually, when workflows
are simply distributed with EnergyPlus, they will point to something like
"..\energyplus.exe", so that they will always point to their own versions
of the tools.  As such, at some point we want to stop keeping these
"built-in" workflows in our ep-launch-3 development.  So maybe it's time we
make some other "built-in" workflows that are *actually* distributed with
ep-launch-3.  Then we can develop them and test with them without this
uncertain future.

**Comment by JasonGlazer** [comment]
BTW, this branch does not run on my computer. I assume due to some hard path.

**Comment by Myoldmopar** [comment]
"does not run", do you mean the E+ workflows, etc.? Or the program as a whole won't start?

**Comment by JasonGlazer** [comment]
Sorry, EPLaunch3 starts up fine. I switch to the EnergyPlus SI workflow and browse to a folder with an IDF and press the RUN button, and I get:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "I:\epRepo\EP-Launch3\eplaunch\interface\workflow_processing.py", line 40, in run
    workflow_response = self.workflow_instance.main(self.run_directory, self.file_name, self.workflow_main_args)
  File "I:\epRepo\EP-Launch3\eplaunch\workflows\default\energyplus.py", line 59, in main
    status_code = subprocess.call([EPlusRunManager.EnergyPlusBinary, '-D', file_name], cwd=run_directory)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified


```

**Comment by JasonGlazer** [comment]
You had said that some hard paths were in there so I didn't really dig into it any more.

**Comment by Myoldmopar** [comment]
Yeah, the paths are pretty straightforward.  Just paste in your path and see if you can get it working for you!  https://github.com/JasonGlazer/EP-Launch3/blob/56e9bab293c63c74ceba65354d01984d00b4d94c/eplaunch/workflows/default/energyplus.py#L15-L18

**Pull request merged**
